Feature/fmfr1315admin dashboard
Crown-Commercial-Service/crown-marketplace pull request #3389
Opened 2022-11-09 10:02 UTC by domducsutcliffe

Finished almost all of the layout of the admin dashboard. Only remaining element is links to the new pages. Current links are placeholders.

2022-11-09 12:35 UTC, tim-s-ccs requested changes
You're nine tenths of the way there, I've just got a few minor changes I'd like you to do. One other thing is to make sure the HTML is indented properly so it is easier to read.

Good work so far!

2022-11-09 12:35 UTC, tim-s-ccs commented on app/views/crown_marketplace/home/index.html.erb
> +</ul>
The text here should be in the translation file

2022-11-09 12:35 UTC, tim-s-ccs commented on app/views/crown_marketplace/home/index.html.erb
> +</ul>
I should have explained yesterday, but these should be wrapped in row and column `div` (like for the section titles). The [GDS](https://design-system.service.gov.uk/styles/layout/#common-layouts) should explain a bit more why.

2022-11-09 15:08 UTC, tim-s-ccs requested changes

2022-11-09 15:08 UTC, tim-s-ccs commented on app/views/crown_marketplace/home/index.html.erb
> +  <main class="govuk-main-wrapper">
Because every page renders within the [application.html.erb](https://github.com/Crown-Commercial-Service/crown-marketplace/blob/master/app/views/layouts/application.html.erb#L39) file, you don't need theses two lines (and the closing tags):
```
<div class="govuk-width-container">
  <main class="govuk-main-wrapper">
```

2022-11-09 15:08 UTC, tim-s-ccs commented on features/support/env.rb
> +Capybara.javascript_driver = :selenium
Make sure you don't commit this change. It's fine for when you want to debug tests but it needs to be headless when GitHub actions runs the tests.

One thing I forgot to say is that you will only be able to see the test appear if the feature has the `@javascript` tag, so you can add that also to help you with debugging.

2022-11-09 16:14 UTC, tim-s-ccs reviewed
You have re-written the tests exactly right :)

2022-11-09 16:23 UTC, domducsutcliffe commented on features/support/env.rb
> +Capybara.javascript_driver = :selenium
Now fixed. Nice re: javascript will not that down

2022-11-10 09:08 UTC, tim-s-ccs commented on app/controllers/facilities_management/buyer_details_controller.rb
> +        render(context)
I think you committed this by accident

2022-11-10 13:56 UTC, tim-s-ccs approved these changes

2022-11-10 14:35 UTC, merged