Email validations for sign up and sign in to avoid SQL Injection flag
Crown-Commercial-Service/crown-marketplace pull request #3410
Opened 2022-11-23 13:52 UTC by domducsutcliffe

2022-11-24 08:33 UTC, tim-s-ccs commented on Gemfile.lock
> +  2.1.4
Looks like you've got an extra space here

2022-11-24 08:49 UTC, tim-s-ccs requested changes
Great job Dom 😃, just a few things for you to look at

2022-11-24 08:49 UTC, tim-s-ccs commented on Gemfile.lock
> +  2.1.4
Looks like you've got an extra space here

2022-11-24 08:49 UTC, tim-s-ccs commented on features/facilities_management/rm3830/cognito/validations/sign_in_validation.feature
> +      #works
This comment is unnecessary and you should have one blank lines between examples

2022-11-24 08:49 UTC, tim-s-ccs commented on features/facilities_management/rm3830/cognito/validations/sign_up_user_validations.feature
> +Scenario Outline: Incorrect email format on sign up & off safelist
What is this test doing that the one on line 38 isn't? Are you really testing that the email is in the correct format?

2022-11-24 08:49 UTC, tim-s-ccs commented on app/services/cognito/sign_up_user.rb
> +    validates_format_of :email, with: /\A[^\s^@]+@[^\s^@]+\z/, message: :blank # validates x@y
These comments are unnecessary

2022-11-24 08:49 UTC, tim-s-ccs commented on app/services/cognito/sign_in_user.rb
> +    validates_format_of :email, with: /\A[^A-Z]*\z/, message: :invalid
You have added validations to make sure the email does not have any capital letters but there are no tests for it (hint: there is a reason we don't need to validate that the email is all lowercase)

2022-11-24 14:41 UTC, domducsutcliffe commented on Gemfile.lock
> +  2.1.4
Yep fixed

2022-11-24 16:05 UTC, tim-s-ccs requested changes
Have a look at the files you've changed and think about what changes should and should not be there https://github.com/Crown-Commercial-Service/crown-marketplace/pull/3410/files

2022-11-24 16:05 UTC, tim-s-ccs commented on app/services/cognito/sign_up_user.rb
> +    validates :email, presence: true, format: { with: /\A[^A-Z]*\z/, message: :invalid }
You did not need to change this line and the email

2022-11-24 16:05 UTC, tim-s-ccs commented on app/services/cognito/sign_up_user.rb
> +    validates_format_of :email, with: /\A[^\s^@]+@[^\s^@]+\z/, message: :blank
Move this line up by one so it is with the other email validation

2022-11-25 08:37 UTC, tim-s-ccs requested changes
Just a couple of other unexpected changes, if you are not sure why they are there you can ask me

2022-11-25 08:37 UTC, tim-s-ccs commented on app/models/facilities_management/rm3830/procurement_contact_detail.rb
> +      validates :email, presence: true, format: { with: /\A([\w+-].?)+@[a-z\d-]+(\.[a-z]+)*\.[a-z]+\z/i }, on: %i[new_invoicing_contact_details new_authorised_representative new_notices_contact_detai
Why have you made changes here?

2022-11-25 08:37 UTC, tim-s-ccs commented on app/services/cognito/forgot_password.rb
> +    validates :email, format: { with: /\A([\w+-].?)+@[a-z\d-]+(\.[a-z]+)*\.[a-z]+\z/i }
Why have you made changes here?

2022-11-25 10:19 UTC, tim-s-ccs approved these changes
LGTM 👍 Now, you just need to do it legacy too

2022-11-25 10:31 UTC, merged