FMFR-1322-add-show-pages-to-manage-users
Crown-Commercial-Service/crown-marketplace pull request #3474
Opened 2023-01-12 12:31 UTC by domducsutcliffe

Ticket: https://crowncommercialservice.atlassian.net/jira/software/c/projects/FMFR/boards/71?modal=detail&selectedIssue=FMFR-1322

Added a show page which summarises the details of users of crown marketplace. Users will use this instead of the Cognito Web portal. Added Feature and RSpec tests to verify this.

2023-01-12 13:58 UTC, tim-s-ccs requested changes
I've left some comments on here.

First of all, look at the ones where I think you have added things accidentally and remove them.
Then take a look at the feature tests that a no longer working.
Finally, when they are, you can look at the other comments and think about what you could do.

2023-01-12 13:58 UTC, tim-s-ccs commented on app/controllers/crown_marketplace/manage_users_controller.rb
> +  end
I don't think this does anything

2023-01-12 13:58 UTC, tim-s-ccs commented on app/services/cognito/admin/roles.rb
> +      end
This may seem like nit picking but, this method is returning text that will appear on the page. This kind of text should only be written in the translation files. My recommendation would be that this method returns a string or symbol that you can then used in the view.

2023-01-12 13:58 UTC, tim-s-ccs commented on app/views/crown_marketplace/manage_users/_user_details_summary.html.erb
> +        <%= t('crown_marketplace.home.manage_users.role') %>
You've made changes here that I don't think you should have

2023-01-12 13:58 UTC, tim-s-ccs commented on app/views/crown_marketplace/manage_users/add_user.html.erb
> +  <div class="govuk-grid-column-full">
I don't think you meant to make this change

2023-01-12 13:58 UTC, tim-s-ccs commented on app/views/crown_marketplace/manage_users/show.html.erb
> +            </a>
All the links on this page should use `link_to` instead of `anchor` tags

2023-01-12 13:58 UTC, tim-s-ccs commented on app/views/crown_marketplace/manage_users/show.html.erb
> +          </strong>
Should this always be blue?

2023-01-12 13:58 UTC, tim-s-ccs commented on app/views/crown_marketplace/manage_users/show.html.erb
> +          <% end %>
What will this show if the user has no roles?

2023-01-12 13:58 UTC, tim-s-ccs commented on app/views/crown_marketplace/manage_users/_user_details_summary.html.erb
> +<dl id="show-user-details-summary" class="govuk-summary-list">
I don't think you meant to make this change

2023-01-12 13:58 UTC, tim-s-ccs commented on features/helpers/crown_marketplace/cognito_helper.rb
> +
You can remove this (it was my fault)

2023-01-12 13:58 UTC, tim-s-ccs commented on spec/controllers/crown_marketplace/manage_users_controller_spec.rb
> +
The tests are good, and you can remove the comments in these now

2023-01-12 13:58 UTC, tim-s-ccs commented on spec/services/cognito/admin/roles_spec.rb
> +  describe '.array_of_users_that_could_edit' do
I think you could add tests for if the user has multiple roles?

2023-01-12 16:39 UTC, domducsutcliffe commented on app/services/cognito/admin/roles.rb
> +      end
Not nitpicking at all! Went down some cul-de-sacs but sorted now. Looks a lot neater in a sense also & yeah I get all text has got to be in the .yml

2023-01-12 17:00 UTC, domducsutcliffe commented on app/views/crown_marketplace/manage_users/show.html.erb
> +            </a>
done

2023-01-12 17:00 UTC, domducsutcliffe commented on app/views/crown_marketplace/manage_users/add_user.html.erb
> +  <div class="govuk-grid-column-full">
i did not

2023-01-12 17:00 UTC, domducsutcliffe commented on app/views/crown_marketplace/manage_users/_user_details_summary.html.erb
> +        <%= t('crown_marketplace.home.manage_users.role') %>
indeed i did not

2023-01-12 17:05 UTC, domducsutcliffe commented on app/views/crown_marketplace/manage_users/_user_details_summary.html.erb
> +<dl id="show-user-details-summary" class="govuk-summary-list">
nope done

2023-01-12 17:05 UTC, domducsutcliffe commented on spec/controllers/crown_marketplace/manage_users_controller_spec.rb
> +
Yep

2023-01-12 17:06 UTC, domducsutcliffe commented
> Should this always be blue? 

Nope will work on this tomorrow AM

2023-01-12 17:07 UTC, domducsutcliffe commented on app/views/crown_marketplace/manage_users/show.html.erb
> +          <% end %>
Will do this tomorrow AM

2023-01-12 17:10 UTC, domducsutcliffe commented on spec/services/cognito/admin/roles_spec.rb
> +  describe '.array_of_users_that_could_edit' do
Will add tomorrow AM

2023-01-12 17:10 UTC, domducsutcliffe commented on features/helpers/crown_marketplace/cognito_helper.rb
> +
done

2023-01-12 17:12 UTC, domducsutcliffe commented on app/views/crown_marketplace/manage_users/show.html.erb
> +          </strong>
Almost certainly not will fix tomoz AM

2023-01-12 19:18 UTC, domducsutcliffe commented on app/views/crown_marketplace/manage_users/show.html.erb
> +          </strong>
Believe this is fixed. Used an IF loop in much the same way as I did for disabled, not that happy with line 67 and think maybe I should do this spade work in the controller? For now I've hard-coded whehter user.confirmation status == 'CONFIRMED' as the thing that this loop turns on. Let me know if you think there's a better approach

2023-01-12 19:23 UTC, domducsutcliffe commented on app/views/crown_marketplace/manage_users/show.html.erb
> +          <% end %>
Should say 'None'. Does now

2023-01-12 19:44 UTC, domducsutcliffe commented on spec/services/cognito/admin/roles_spec.rb
> +  describe '.array_of_users_that_could_edit' do
Cool done for the array one and the minimum role one. All passing

2023-01-13 08:24 UTC, tim-s-ccs requested changes
Just a few more things to look at

2023-01-13 08:24 UTC, tim-s-ccs commented on features/helpers/crown_marketplace/cognito_helper.rb
> +# attributes
You can still remove this comment I accidentally left in

2023-01-13 08:24 UTC, tim-s-ccs commented on spec/services/cognito/admin/roles_spec.rb
> +  describe '.minimum_editor_role' do
You need to update the 'it' parts of this RSpec since you change the method and some of them are "not telling the truth" as it were

2023-01-13 08:24 UTC, tim-s-ccs commented on app/views/crown_marketplace/manage_users/show.html.erb
> +            <%= link_to'#', class:'govuk-link'%>
These links are not right, I think yo should try running the rails server and try viewing the page as it may help you debug it.

2023-01-13 10:51 UTC, domducsutcliffe commented on features/helpers/crown_marketplace/cognito_helper.rb
> +# attributes
Ah apologies I thought the extra line was the problem. Done

2023-01-13 10:54 UTC, domducsutcliffe commented on spec/services/cognito/admin/roles_spec.rb
> +  describe '.minimum_editor_role' do
Fixed some mistakes in the titles and changed the phrasing to 'it returns [role] translation' - accurate?

2023-01-13 13:38 UTC, tim-s-ccs approved these changes

2023-01-13 14:24 UTC, merged