FMFR-1327 - Add ability to edit user service access
Crown-Commercial-Service/crown-marketplace pull request #3486
Opened 2023-01-16 12:16 UTC by tim-s-ccs

Ticket: [FMFR-1327](https://crowncommercialservice.atlassian.net/browse/FMFR-1327)

In this commit I have added the ability to edit a user’s service access. Before I started this I first refactored some of the work for the show users page so that it could be more easily shared between the controller methods.

I’ve added tests for all my changes including:
- Specs for the new helper methods
- Specs for the changes to roles
- Specs for the controller (both edit and update)
- Feature tests for editing and updating the user

[FMFR-1327]: https://crowncommercialservice.atlassian.net/browse/FMFR-1327?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2023-01-16 14:43 UTC, domducsutcliffe commented on app/controllers/crown_marketplace/manage_users_controller.rb
> +    [['buyer'], ['ccs_employee']].include?(roles)
Only buyers and CCS Employees need service access? Why is that?

2023-01-16 15:14 UTC, domducsutcliffe commented on app/controllers/crown_marketplace/manage_users_controller.rb
> +        { section => [] }
why return an empty array though here?

2023-01-16 15:38 UTC, tim-s-ccs commented on app/controllers/crown_marketplace/manage_users_controller.rb
> +        { section => [] }
This might be easier to show you but I'll try and explain.

On checkbox or radio button pages, if nothing is selected then the data that is sent to the controller is not that nothing is selected (`section => []`) but is instead nothing at all. Therefore, when we would assign attributes we would not be removing any of our selections but instead nothing would change. This would then trip up validations.

Again, this is probably just easier to show you

2023-01-16 17:24 UTC, domducsutcliffe approved these changes

2023-01-16 17:50 UTC, domducsutcliffe requested changes
Code climate is upset at the number of methods in the ManageUser controller. We have 27 and if < 20 Code climate throws an error. What do you reckon?

2023-01-17 08:55 UTC, tim-s-ccs commented
> Code climate is upset at the number of methods in the ManageUser controller. We have 27 and if < 20 Code climate throws an error. What do you reckon?

There are things we could do to make code climate happy but these would involve moving some of the methods out of the controller into a concern. However this is not the right thing to do as we wont be sharing any of this code between controllers which we would be trying to satisfy Code Climate for the sake of it. In this case, I think it is fine to bypass Code Climates issue.

2023-01-17 10:17 UTC, domducsutcliffe approved these changes

2023-01-17 10:17 UTC, merged