Added a feature where the user table only renders when a string is present in the search box
Crown-Commercial-Service/crown-marketplace pull request #3511
Opened 2023-01-26 12:18 UTC by domducsutcliffe

Issue: https://crowncommercialservice.atlassian.net/jira/software/c/projects/FMFR/boards/71?modal=detail&selectedIssue=FMFR-1338

I have included an additional feature test.

2023-01-27 12:33 UTC, tim-s-ccs requested changes
Just a couple of things for you to think about plus one change (add the step to more feature tests)

2023-01-27 12:33 UTC, tim-s-ccs commented on features/crown_marketplace/manage_users/user_admin/validations/find_users_javascript_enabled_validation.feature
> +    Then I should not see users table
You should add this step definition to all the places where you would not expected to see the users table.

2023-01-27 12:33 UTC, tim-s-ccs commented on app/controllers/crown_marketplace/manage_users_controller.rb
> +    @form_submitted_success = !(@search[:error] || params[:email].blank?)
No need to make a change but you could have just put the condition in the if statement in `_users_table.html.erb` template instead of creating an instance variable.

2023-01-27 12:33 UTC, tim-s-ccs commented on features/step_definitions/crown_marketplace/manage_users_steps.rb
> +  expect(manage_users_page).not_to have_content('No users were found with that email address')
No need to make a change as the context of where you use this step is fine but this step is not necessarily checking there is no table, it's checking to see if that text is not there which is not quite the same thing.

2023-01-27 12:36 UTC, domducsutcliffe commented on app/controllers/crown_marketplace/manage_users_controller.rb
> +    @form_submitted_success = !(@search[:error] || params[:email].blank?)
True! My thinking of doing it this way is that in my mind the 'business logic' should stay in the controller and the view should contain only the visual elements. That's a distinction I've just picked up via my understanding of the MVC model though, so happy to be corrected?

2023-01-27 13:23 UTC, tim-s-ccs commented on app/controllers/crown_marketplace/manage_users_controller.rb
> +    @form_submitted_success = !(@search[:error] || params[:email].blank?)
I think that is the right view to have but I would not class this as business logic. It is a grey area (as things like this often are) but I would think of business logic more of fetching data and determining what should happen (should we redirect and things like that).

This is more view logic where we are deciding whether or not to show the table in the view. I'm not sure I've explained this very well but, as this is more to do with the display of the table, it should probably just go in the view.

Again, it's fine as it is so it is up to you if you want to change or not.

2023-01-27 13:25 UTC, domducsutcliffe commented on features/step_definitions/crown_marketplace/manage_users_steps.rb
> +  expect(manage_users_page).not_to have_content('No users were found with that email address')
Would a more precise test, be whether or not there's a CSS element with a table ID present in the code? I've seen that elsewhere in the codebase

2023-01-27 13:28 UTC, domducsutcliffe commented on features/crown_marketplace/manage_users/user_admin/validations/find_users_javascript_enabled_validation.feature
> +    Then I should not see users table
should be done now!

2023-01-27 13:30 UTC, domducsutcliffe commented on app/controllers/crown_marketplace/manage_users_controller.rb
> +    @form_submitted_success = !(@search[:error] || params[:email].blank?)
I think I will change this as it's not logic particular to the business it's about the page rendering in a way that's not going to confuse the user. 

Will move this logic from controller to the view.

2023-01-27 13:32 UTC, tim-s-ccs commented on features/step_definitions/crown_marketplace/manage_users_steps.rb
> +  expect(manage_users_page).not_to have_content('No users were found with that email address')
Yes, as a hint the table is contained within a `div` which has the ID of `#users-table`.
Try and figure out how you can check this div is empty using Capybara by looking at other steps or the docs.

2023-01-27 13:37 UTC, domducsutcliffe commented on features/step_definitions/crown_marketplace/manage_users_steps.rb
> +  expect(manage_users_page).not_to have_content('No users were found with that email address')
Cheers gonna grab some lunch so will look at this afternoon :)

2023-01-27 16:16 UTC, domducsutcliffe commented on features/step_definitions/crown_marketplace/manage_users_steps.rb
> +  expect(manage_users_page).not_to have_content('No users were found with that email address')
Resolved by targetting the css of the table in the partial. What do you think?

2023-01-29 12:26 UTC, domducsutcliffe commented
Believe I've made all the needed changes @tim-s-ccs

2023-01-30 10:50 UTC, tim-s-ccs approved these changes

2023-01-30 10:50 UTC, merged